enableSodiumMenu = true
cloudCulling = true
signTextCulling = true
rainCulling = true
useBlockStateCulling = false
useCustomItemFrameRenderer = true
itemFrameMapCulling = true
useItemFrameLOD = true
itemFrameLODRange = 384
useItemFrame3FaceCulling = true
itemFrame3FaceCullingRange = 12.0
leavesCullingMode = "DEPTH"
leavesCullingAmount = 3
includeMangroveRoots = false
powderSnowCulling = true
useOnModdedBlocksByDefault = true

[modCompatibility]
adorn = true
mcwfences = true
farmersdelight = true
barteringstation = true
mcwroofs = true
croptopia = true
campanion = true
alloy_forgery = true
cookingforblockheads = true
spectrum = true
mcwwindows = true
pfm = true
enderore = true
another_furniture = true
twigs = true
redstonebits = true
farmingforblockheads = true
mcwpaths = true
yigd = true
mcwbridges = true
mcwlights = true
mcwtrpdoors = true
milk = true
led = true
handcrafted = true
minecarttweaks = true
chisel = true
dankstorage = true
charm = true
compressed = true
customportalapi = true
mcwdoors = true
ironchests = true
chiselsandbits = true
botania = true
supplementaries = true
factory_blocks = true
magnumtorch = true
dustrial_decor = true
create = true
geodes = true
forgero = true
extended_drawers = true
netherchest = true
create_crystal_clear = true
xps = true
architects_palette = true
minecraft = true
fwaystones = true
merequester = true
expandedstorage = true
createaddition = true
appbot = true
ae2 = true
decorative_blocks = true
creeperoverhaul = true
tradingpost = true
moderndynamics = true
mining_dims = true
