# LambDynamicLights configuration.
# The dynamic lights mode
mode = "fancy"

# Light sources settings.
[light_sources]
	# Enable entities light source.
	entities = true
	# Enable first-person player light source.
	self = true
	# Enable block entities light source.
	block_entities = true
	# Enables water-sensitive light sources check. This means that water-sensitive items will not light up when submerged in water.
	water_sensitive_check = true
	# Creeper lighting mode. May be off, simple or fancy.
	creeper = "simple"
	# TNT lighting mode. May be off, simple or fancy.
	tnt = "off"

	[light_sources.settings]

		[light_sources.settings.entities]

			[light_sources.settings.entities.minecraft]
				glow_item_frame = false
				player = true
				sheep = true
				cow = true
				horse = true
				chicken = true
				bee = true
				turtle = true
				glow_squid = true
				bat = true
				squid = true
				zombie = true
				skeleton = true
				cave_spider = true
				creeper = true
				spider = true
				salmon = true
				pig = true
				item = true
				donkey = true
				axolotl = true
				zombie_villager = true
				ocelot = true
				enderman = true
				tropical_fish = true
				drowned = true
				cod = true
				dolphin = true
				parrot = true
				witch = true
				villager = true
				tnt_minecart = true
				chest_minecart = true
				fox = true
				goat = true
				armor_stand = true
				wolf = true
				rabbit = true
				pillager = true
				iron_golem = true
				cat = true
				painting = true
				vindicator = true
				slime = true
				polar_bear = true
				stray = true
				llama = true
				evoker = true
				item_frame = true
				arrow = true
				husk = true
				illusioner = true
				wither_skeleton = true
				frog = true
				pufferfish = true
				allay = true
				hoglin = true
				phantom = true
				wandering_trader = true
				trader_llama = true
				llama_spit = true

			[light_sources.settings.entities.creeperoverhaul]
				cave_creeper = true
				dripstone_creeper = true
				jungle_creeper = true
				dark_oak_creeper = true
				bamboo_creeper = true
				hills_creeper = true
				snowy_creeper = true
				spruce_creeper = true
				savannah_creeper = true
				desert_creeper = true
				beach_creeper = true
				swamp_creeper = true
				badlands_creeper = true

			[light_sources.settings.entities.wondrouswilds]
				firefly = true
				woodpecker = true

			[light_sources.settings.entities.lovely_snails]
				snail = true

			[light_sources.settings.entities.charm]
				moobloom = true

			[light_sources.settings.entities.create]
				stationary_contraption = true

			[light_sources.settings.entities.farmingforblockheads]
				merchant = true

			[light_sources.settings.entities.reaping]
				reaping_pillager = true

